### ISSUE TITLE
Project is now dead ?

### ISSUE THREAD

**Issue by gedw99** [planetdecred/godcr#1053]
no code changed for ages ? Why did this all stop ?

**Comment by xaur** [comment]
@gedw99 I'm not a member of the GoDCR team but since this has been silent I'll answer.

[Funding proposal](https://proposals.decred.org/record/0ef42e5) for GoDCR and mobile wallets was rejected by Decred stakeholders in July 2022. Last code changes were merged in August. On Aug 5 the team has announced in Matrix that they will no longer work on GoDCR and focus on other non-Decred work that is fundable.

So far noone has stepped up to continue the project but the source code is still there for anyone willing to pick it up.

**Comment by dreacot** [comment]
@gedw99 there's a replacement project here https://github.com/crypto-power/cryptopower
