### ISSUE TITLE
update: scroll on restore page

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#204]
The list of editor widgets on the restore page don't scroll smoothly, it should scroll smoothly just as it did before the update.

**Comment by oshorefueled** [comment]
The issue seems to be with Gioui upstream. The list scrolls but it can only be done with scroll gestures using the mouse pointer at the side of the list. I created an issue upstream  https://todo.sr.ht/~eliasnaur/gio/148

**Comment by ghost** [comment]
I will have a look at this issue because in my experience so far with Gio it is almost always because expensive computation is in the render queue that causes slow framerate and sometimes flicker (most often on MacOS, probably due to the back end). Usually the best solution is to have a channel that receives state changes and keep the computation in a separate thread.

**Comment by ghost** [comment]
I'm set up to work now, and in the office... this looks like a good one for me to start with. 

The list widget in Gio is kinda really a dirty hack. It doesn't have any proper way to track the vertical position, I started working on an offscreen rendering using headless context but my work was interrupted. 

I don't really see why it should be laid out with a list widget at all. I will rework the layout to a more flexible layout and add some keyboard navigation to it so you can press tab/shift tab to move back and forth and make the layout react to the window size. Any specific requests for how it should be please let me know. I will update here when I have something working.

**Comment by oshorefueled** [comment]
This will be resolved on issue #217
