### ISSUE TITLE
Implement new GUI mockups

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#259]
Some mockups have been provided as an upgrade to the current godcr UI. One of the provided mockups should be selected and implemented into the godcr codebase

These are links to the sketch artboard containing the mockups

1. https://www.sketch.com/s/34b25f95-6ea5-4d3c-9a2c-f3965b8c156a/a/DG21Ea/play
2. https://www.sketch.com/s/34b25f95-6ea5-4d3c-9a2c-f3965b8c156a/a/laelKK/play

**Previews**

**1.**
<img src="https://user-images.githubusercontent.com/25265396/93808325-bb15d500-fc43-11ea-9b69-dc10e59777b6.png" width="75%">

**2.**
<img src="https://user-images.githubusercontent.com/25265396/93808579-18aa2180-fc44-11ea-8ac4-b07a2849ce43.png" width="75%">

**Comment by morphymore** [comment]
Hey @dreacot, here's an updated mockup (only Overview for now) to further improve the ease of use.

### Updates
- Add label text to tabs
- Collapse/expand tab
### Links
- [Prototype (demo: collapse/expand)](https://www.figma.com/proto/hlouexhLuHjsq11DX4dcN8/godcr?node-id=65%3A4320&viewport=161%2C155%2C1&scaling=min-zoom) (to feel)
- [Specs](https://www.figma.com/file/hlouexhLuHjsq11DX4dcN8/godcr?node-id=65%3A4319) (to implement)

Note that you'll need to log in to Figma in order to see the specs (a free account will do), or you'll only see static images. Let me know if you encounter any issues.

### Previews
<img width="800" alt="Overview_collapsed" src="https://user-images.githubusercontent.com/13583235/93973134-47d8a400-fda6-11ea-8bfc-dc56f194cdd5.png">
<img width="800" alt="Overview_expanded" src="https://user-images.githubusercontent.com/13583235/93973143-4b6c2b00-fda6-11ea-9456-887a43f3724f.png">

**Comment by dreacot** [comment]
Hello @morphymore, are the icons used in the mockup available in png format?

**Comment by morphymore** [comment]
@dreacot Yes. You can export them directly from the specs file.
1. Select the icon on the mockup (holding down `ctrl` or `cmd` could be handy)
2. Check the left menu to make sure you have the correct selection (e.g. `ic_[name]_[size]`)
3. Export in the right section (under **Export**)

Example:
<img width="1440" alt="ScreenShot" src="https://user-images.githubusercontent.com/13583235/94722257-9f1fdb00-0389-11eb-9a79-a4de6565bd68.png">
