### ISSUE TITLE
Recent transaction shuffle on overveiw page.

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#551]
For some reason, when the left navigation button of the overview page is clicked multiple times, the last 2 recent transactions seem to shuffle.
![ezgif com-gif-maker(5)](https://user-images.githubusercontent.com/27733432/128673489-cb8839e2-15cd-4d69-b709-e11e1e85e23d.gif)

**Comment by devchoplife** [comment]
I am unable to reproduce the error.

**Comment by beansgum** [comment]
I'm able to recreate by having multi wallets and multi-wallet transactions displayed on the overview page. Since the transactions are not sorted in godcr and are gotten directly from dcrlibwallet, I believe the bug is from [this dcrlibwallet function](https://github.com/planetdecred/dcrlibwallet/blob/master/transactions.go#L120). In dcrlibwallet, the wallets are stored in a map and that means looping through the map can return the wallets in an inconsistent order.

**Comment by Sirmorrison** [comment]
not reproducible anymore.
