### ISSUE TITLE
Prevent duplication of wallets when importing a wallet from seeds by validating wallet seed against existing wallets.

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#816]
Currently, if i have a wallet that the seed is backed up, i can re-import that wallet into the application.

This is bad because it give a false total balance and the wallet address are same as the default and as such transactions will be duplicated.

Original wallet.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/27733432/159470380-7f08a73a-9c16-4484-9c7d-d0f88b0d3a6e.png">

duplicated
<img width="795" alt="image" src="https://user-images.githubusercontent.com/27733432/159470557-6b8db7c2-15a7-46aa-89f2-30e9795fe5a4.png">

HOW TO REPRODUCE
=================
Back up and already existing wallet seed, then try importing wallet from existing seed of the just backed up wallet.

**Comment by itswisdomagain** [comment]
I think this should also apply to adding watch-only wallets using xpub of an existing wallet. It'll result in similar issues as presented above, the only difference being that the watch-only wallet cannot be used to send funds.

In a similar vein, if a watch-only wallet already exists and a user tries to import a new wallet using the seed for the existing watch-only wallet, the app should probably show a warning and migrate the watch-only wallet to a full wallet rather than keeping the watch-only wallet and importing a new wallet that has the same tx history and balance as the existing watch-only wallet.

**Comment by dreacot** [comment]
resolved by https://github.com/planetdecred/godcr/pull/891
