### ISSUE TITLE
Info icon inconsistent between mouse over or click

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#822]
The info icons are not consistently implemented. Some require click and some are mouse-over. Fix the new governance pages to mouse-over for consistency.

<img width="798" alt="Screen Shot 2022-03-23 at 11 11 32 AM" src="https://user-images.githubusercontent.com/66281245/159768188-80e4c407-389a-48dd-b114-df60d3c4a839.png">

**Comment by Sirmorrison** [comment]
@monsa00 i would suggest we use click for now instead of the Hover as the hover/tooltip widget needs some major refactoring.

On click of the info icon, we can add these information in a modal and exit with the got it button.

<img width="128" alt="image" src="https://user-images.githubusercontent.com/27733432/163603721-beb58635-48b6-4c98-b425-337a67ac6d95.png">
