### ISSUE TITLE
Rename mixed unmixed accounts during manual setup

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#858]
After manual setup of cspp the accounts are not currently renamed. Auto setup does rename the accounts.

<img width="778" alt="Screen Shot 2022-03-30 at 11 46 06 AM" src="https://user-images.githubusercontent.com/66281245/160910222-e198a2f2-b0bc-4ddf-8327-efe07b5c7e16.png">

**Comment by Sirmorrison** [comment]
By default, when auto setting up the mixer accounts, the default account name is `Mixed and unmixed` and these can also renamed from `mixed` and `unmixed` to any name of your choice.

What manual setup does is enable the user decide which account to use for the set up rather than the automatic account creation.

Manual set up removes the option of creating additional accounts. 

After pointing to the desired accounts, the user can choose to rename it or leave it so.

**Comment by dreacot** [comment]
Yeah, what sirmorrison has explained is correct

**Comment by monsa00** [comment]
This is so that instead of having to remember that account-1 is unmixed for example, it will say `unmixed` in the UI instead of `account-1`. It makes it more intuitive to use godcr once privacy has been enabled, so that you know exactly what account you're looking at when using the functions. It would be identical to renaming the account in the wallet view, but done automatically based on what the user mapped.

<img width="609" alt="Screen Shot 2022-04-22 at 11 30 18 AM" src="https://user-images.githubusercontent.com/66281245/164773571-5b345d89-1fd8-4d30-9d20-31ea576fd098.png">
