### ISSUE TITLE
app crashes while deleting a wallet

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#865]
I encountered this error while deleting two wallets back to back. 

I had 7 wallets, I then proceeded to delete one, which was successfully deleted, i then immediately proceeded to delete another one before the crash occurred

**See log below:**

```
2022-03-31 17:10:15.047 [INF] DLWL: Deleting Wallet
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x92f738]

goroutine 82 [running]:
[decred.org/dcrwallet/v2/wallet.(*Wallet).AccountBalance(0x0,](http://decred.org/dcrwallet/v2/wallet.(*Wallet).AccountBalance(0x0,) 0x1ed43d8, 0xc004d3c040, 0x200000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/kennedy/Projects/pkg/mod/[decred.org/dcrwallet/v2@v2.0.1/wallet/wallet.go:1955](http://decred.org/dcrwallet/v2@v2.0.1/wallet/wallet.go:1955) +0xb8
[github.com/planetdecred/dcrlibwallet.(*Wallet).GetAccountBalance(0xc0001d8960,](http://github.com/planetdecred/dcrlibwallet.(*Wallet).GetAccountBalance(0xc0001d8960,) 0x0, 0x3, 0xc004bf4000, 0x0)
        /home/kennedy/Projects/pkg/mod/[github.com/planetdecred/dcrlibwallet@v1.6.2-0.20220315164532-e871b673497a/accounts.go:108](http://github.com/planetdecred/dcrlibwallet@v1.6.2-0.20220315164532-e871b673497a/accounts.go:108) +0x12f
[github.com/planetdecred/dcrlibwallet.(*Wallet).GetAccountsRaw(0xc0001d8960,](http://github.com/planetdecred/dcrlibwallet.(*Wallet).GetAccountsRaw(0xc0001d8960,) 0xc004d3c280, 0x0, 0x0)
        /home/kennedy/Projects/pkg/mod/[github.com/planetdecred/dcrlibwallet@v1.6.2-0.20220315164532-e871b673497a/accounts.go:41](http://github.com/planetdecred/dcrlibwallet@v1.6.2-0.20220315164532-e871b673497a/accounts.go:41) +0x13c
[github.com/planetdecred/godcr/ui/page.(*MainPage).CalculateTotalWalletsBalance(0xc001969800,](http://github.com/planetdecred/godcr/ui/page.(*MainPage).CalculateTotalWalletsBalance(0xc001969800,) 0xc00016c180, 0xc0004e1288, 0xc00195cdf0)
        /home/kennedy/Projects/src/[github.com/planetdecred/godcr/ui/page/main_page.go:309](http://github.com/planetdecred/godcr/ui/page/main_page.go:309) +0x9d
[github.com/planetdecred/godcr/ui/page.(*MainPage).updateBalance(0xc001969800)](http://github.com/planetdecred/godcr/ui/page.(*MainPage).updateBalance(0xc001969800))
        /home/kennedy/Projects/src/[github.com/planetdecred/godcr/ui/page/main_page.go:287](http://github.com/planetdecred/godcr/ui/page/main_page.go:287) +0x2f
[github.com/planetdecred/godcr/ui/page.(*MainPage).listenForNotifications.func1(0xc001969800)](http://github.com/planetdecred/godcr/ui/page.(*MainPage).listenForNotifications.func1(0xc001969800))
        /home/kennedy/Projects/src/[github.com/planetdecred/godcr/ui/page/main_page.go:880](http://github.com/planetdecred/godcr/ui/page/main_page.go:880) +0x1d7
created by [github.com/planetdecred/godcr/ui/page.(*MainPage).listenForNotifications](http://github.com/planetdecred/godcr/ui/page.(*MainPage).listenForNotifications)
        /home/kennedy/Projects/src/[github.com/planetdecred/godcr/ui/page/main_page.go:842](http://github.com/planetdecred/godcr/ui/page/main_page.go:842) +0x44f
```

**Comment by Sirmorrison** [comment]
I was unable to reproduce this issue while testing.

However, looking through the error, i see it happened here
<img width="616" alt="image" src="https://user-images.githubusercontent.com/27733432/162495987-fdc23df5-c950-4257-bebb-b0eb7dcd2568.png">

Kindly confirm the circumstances around this process. Where you syncing the wallet before trying to delete it?

**Comment by dreacot** [comment]
my wallet was fully synced, but seeing as deleting a wallet disconnects from the network, and then connects back to the network after deleting, it's possible that the sync/re-connection process has started when i tried deleting the second wallet, as i did both of them immediately after the other

**Comment by LasTshaMAN** [comment]
Hello, I got interested and looked into it a bit, can suggest the following explanation for why this happens (would like your feedback on it, obviously :),

the issue is probably caused by accessing [wallets](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L31-L31) map in un-sychronized way (without properly using mutexes/channels as is required by [go memory model](https://go.dev/ref/mem)) from multiple different go-routines,

once user deletes his wallet in UI (as I understand the code, it happens [here](https://github.com/planetdecred/godcr/blob/b662b556246775ac103756b39ac7f593ae039c2f/ui/page/wallets/wallet_settings_page.go#L282-L282)) from, lets call it, go-routine-1),
- [this happens](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/internal/loader/loader.go#L406-L406) (lets mark it as **)
- and then [wallets](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L31-L31) map gets updated: [wallet item gets deleted](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L550-L550)

while from view-point of [go-routine-2](https://github.com/planetdecred/godcr/blob/b662b556246775ac103756b39ac7f593ae039c2f/ui/page/main_page.go#L821-L821) (where executes the code, mentioned by @Sirmorrison above) wallet object is still present in [wallets](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L31-L31) map and `updateBalance` gets called on it (while ** change has already been noticed by go-routine-2, but deletion from map hasn't been due to lack of synchorization between go-routines), and panics because of dereferencing `w.db` where `w` is `nil` [here](https://github.com/decred/dcrwallet/blob/b5fa3cc413ac6905f38d7db8bbf0a1af81aec173/wallet/wallet.go#L1955) ...

The solution could be to synchronize access to the [problematic map](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L31-L31) (and possibly [badWallets map](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L32), because it likely suffers from the same issues) via a dedicated mutex, what do you think ?

At any rate, it seems to me [MultiWallet](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L25) is not safe (`wallets` part) for concurrent use, while it likely is meant to be.

**Comment by dreacot** [comment]
> Hello, I got interested and looked into it a bit, can suggest the following explanation for why this happens (would like your feedback on it, obviously :),
> 
> the issue is probably caused by accessing [wallets](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L31-L31) map in un-sychronized way (without properly using mutexes/channels as is required by [go memory model](https://go.dev/ref/mem)) from multiple different go-routines,
> 
> once user deletes his wallet in UI (as I understand the code, it happens [here](https://github.com/planetdecred/godcr/blob/b662b556246775ac103756b39ac7f593ae039c2f/ui/page/wallets/wallet_settings_page.go#L282-L282)) from, lets call it, go-routine-1),
> 
> * [this happens](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/internal/loader/loader.go#L406-L406) (lets mark it as **)
> * and then [wallets](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L31-L31) map gets updated: [wallet item gets deleted](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L550-L550)
> 
> while from view-point of [go-routine-2](https://github.com/planetdecred/godcr/blob/b662b556246775ac103756b39ac7f593ae039c2f/ui/page/main_page.go#L821-L821) (where executes the code, mentioned by @Sirmorrison above) wallet object is still present in [wallets](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L31-L31) map and `updateBalance` gets called on it (while ** change has already been noticed by go-routine-2, but deletion from map hasn't been due to lack of synchorization between go-routines), and panics because of dereferencing `w.db` where `w` is `nil` [here](https://github.com/decred/dcrwallet/blob/b5fa3cc413ac6905f38d7db8bbf0a1af81aec173/wallet/wallet.go#L1955) ...
> 
> The solution could be to synchronize access to the [problematic map](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L31-L31) (and possibly [badWallets map](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L32), because it likely suffers from the same issues) via a dedicated mutex, what do you think ?
> 
> At any rate, it seems to me [MultiWallet](https://github.com/planetdecred/dcrlibwallet/blob/62281e38109a8b942c291cae07d9db2aaf2edb61/multiwallet.go#L25) is not safe (`wallets` part) for concurrent use, while it likely is meant to be.

Thanks for sharing you idea, and also, tanks for painting a very vivid roadmap of your findings.

From your 4th paragraph, `while from view-point of [go-routine-2](https://github.com/planetdecred/godcr/blob/b662b556246775ac103756b39ac7f593ae039c2f/ui/page/main_page.go#L821-L821)...` it's true that the `updateBalance` method tries to reference a non existent map.

a solution would be worked on soon.

however, would you like to work on this?

**Comment by LasTshaMAN** [comment]
> however, would you like to work on this?

From what I figured out, this should resolve it: https://github.com/planetdecred/dcrlibwallet/pull/252

or do you have a different solution in mind ?
